tweetrace/justgivingbadges/urls.py
from django.conf.urls.defaults import patterns, include, url

from justgivingbadges.views import (register, callback,
            home, fundraiser_page, supporter_page, top_fundraisers)

urlpatterns = patterns('',
    url(r'^register/$', register, name='register'),
    url(r'^callback/$', callback, name='twitter-oauth-callback'),

    url(r'^$', home, name='home-page'),
    url(r'^top_fundraisers/$', top_fundraisers, name='top-fundraisers'),
    url(r'^fundraiser/(?P<fundraiser_id>\w+)/$',
        fundraiser_page, name='fundraiser-page'),
    url(r'^fundraiser/(?P<fundraiser_id>\w+)/supporter/(?P<supporter_name>\w+)/$',
        supporter_page, name='supporter-page'),
)

tweetrace/urls.py
from django.conf.urls.defaults import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^', include('tweetrace.justgivingbadges.urls')),

    url(r'^admin/', include(admin.site.urls)),
)

tweetrace/justgivingbadges/models.py
from django.db import models
from django.contrib.auth.models import User

class FundRaiserProfile(models.Model):
    jg_page_id = models.CharField(max_length=200, primary_key=True)
    user = models.OneToOneField(User, blank=True, null=True, default=None)

    page_score = models.IntegerField(blank=True, null=True, default=None, db_index=True)

    twitter_id = models.BigIntegerField(null=True, blank=True)
    access_token = models.CharField(max_length=200,null=True, blank=True)
    access_token_secret = models.CharField(max_length=200,null=True, blank=True)
    twitter_username = models.CharField(max_length=200,null=True, blank=True)

tweetrace/justgivingbadges/forms.py
import re

from django import forms
from justgivingbadges.models import FundRaiserProfile

JG_URL = re.compile(
    r"""\b                          # start at word boundary
        (?:https?://)?              # protocol optional
        (?:www\d{0,3}\.)?           # server optionl
        (?:justgiving\.com/)?       # domain optional
        ([a-zA-Z0-9-]+)             # capture path
        (.*)                        # capture the rest
    """, re.IGNORECASE|re.UNICODE|re.VERBOSE);

def cleaned_page_id(candidate_id, strict=False):
    m = JG_URL.match(candidate_id)
    if m:
        page_id = m.group(1)
        print m.group(1)
        if strict and m.group(2):
            print m.group(2)
            return None
        else:
            return page_id
    else:
        return None

class FundRaiserRegistration(forms.Form):

    def clean_jg_page(self):
        jg_page = self.cleaned_data['jg_page']
        jg_page = cleaned_page_id(jg_page, strict=True)
        if not jg_page:
            raise forms.ValidationError('That\'s not a valid JustGiving Page')
        return jg_page

    email = forms.EmailField(
        label="Your email address")
    jg_page = forms.CharField(
        label="Your JustGiving Page")
    jg_password = forms.CharField(
        widget=forms.PasswordInput, label="Your JustGiving Password")

tweetrace/justgivingbadges/views.py
import hashlib
from oauth import oauth
from tweepy.auth import OAuthHandler
import json

from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render_to_response, get_object_or_404
from django.template import RequestContext
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.utils.functional import wraps

from justgivingbadges.forms import FundRaiserRegistration
from justgivingbadges.models import FundRaiserProfile

from linkwatcher.models import Mention, TwitterUser, FundRaisingPageStats

from django.conf import settings

class Sticker(object):
    def __init__(self, image_url, name):
        self.name = name
        self.image_url = image_url
    def __unicode__(self):
        return self.name
GOLD = Sticker('img/gold_sticker_small.png', 'gold')
SILVER = Sticker('img/silver_sticker_small.png', 'silver')
BRONZE = Sticker('img/bronze_sticker_small.png', 'bronze')

def return_json(view):
    def wrapper(request, *args, **kwargs):
        try:
            data = view(request, *args, **kwargs)
            status = 200
        except Exception, e:
            data = {'error': str(e)}
            status = 400
        json_str = json.dumps(data, cls=JustGivingBadgesJSONEncoder)
        return HttpResponse(json_str, mimetype='application/json', status=status)
    return wraps(view)(wrapper)

def _user_from_reg_form(form):
    email = form.cleaned_data['email']
    return User.objects.create_user(
            hashlib.md5(email).hexdigest()[:16],
            password=form.cleaned_data['jg_password'],
            email=email)

def _profile_from_reg_form(form, user):
    profile, created = FundRaiserProfile.objects.get_or_create(
            jg_page_id=form.cleaned_data['jg_page'],
            defaults={'user': user}
        )
    if not created:
        if profile.user is None:
            profile.user = user
            profile.save()
        else:
            raise ValueError
    return profile

def _top_fundraisers():
    fundraisers = list(FundRaiserProfile.objects.order_by('-page_score')[:3])
    for fundraiser in fundraisers:
        _extend_profile(fundraiser)
    return fundraisers

def _extend_profile(fundraiser):
    try:
        stats = FundRaisingPageStats.objects.get(fundraiser=fundraiser)
        fundraiser.event_name = stats.result_from_jg['eventName']
        fundraiser.owner_name = stats.result_from_jg['owner']
        fundraiser.total_raised = stats.result_from_jg['totalRaisedOnline']
    except FundRaisingPageStats.DoesNotExist:
        fundraiser.event_name, fundraiser.owner_name, fundraiser.total_raised = ('', '', '')

def home(request):
    fundraiser = None
    if request.user.is_authenticated():
        fundraiser = _extend_profile(request.user.get_profile())
    top_fundraisers = _top_fundraisers()

    return render_to_response('home.html',
        {'fundraiser': fundraiser,
         'top_fundraisers': top_fundraisers},
        context_instance=RequestContext(request))

def register(request):
    if request.method == 'POST':
        form = FundRaiserRegistration(request.POST)
        if form.is_valid():
            # partially create user, and store unauthed token
            user = _user_from_reg_form(form)
            try:
                profile = _profile_from_reg_form(form, user)
            except ValueError:
                return HttpResponse('that page is already registered')

            request.session['user_id'] = user.pk
            handler = OAuthHandler(settings.TWITTER_CONSUMER_KEY,
                    settings.TWITTER_CONSUMER_SECRET,
                    callback='http://www.justgivingthanks.com/callback/',
                    secure=True)
            auth_url = handler.get_authorization_url()
            request.session['unauthed_token'] = handler.request_token.to_string()
            print 'created user, got token, redirecting to %s' % (auth_url)
            return HttpResponseRedirect(auth_url)
    else:
        form = FundRaiserRegistration() # An unbound form

    return render_to_response('registration.html',
            {'form': form},
            context_instance=RequestContext(request))

def callback(request):
    unauthed_token = request.session.get('unauthed_token', None)
    if not unauthed_token:
        return HttpResponse("No un-authed token cookie")
    token = oauth.OAuthToken.from_string(unauthed_token)
    if token.key != request.GET.get('oauth_token', 'no-token'):
        return HttpResponse("Something went wrong! Tokens do not match")
    verifier = request.GET.get('oauth_verifier')
    handler = OAuthHandler(settings.TWITTER_CONSUMER_KEY,
               settings.TWITTER_CONSUMER_SECRET,
               secure=True)
    handler.request_token = token
    access_token = handler.get_access_token(verifier)

    # save token against user
    user = User.objects.get(pk=request.session['user_id'])
    profile = user.get_profile()
    profile.access_token = access_token.key
    profile.access_token_secret = access_token.secret
    profile.save()

    redirect = reverse('fundraiser-page', kwargs={'fundraiser_id': profile.jg_page_id})
    return HttpResponseRedirect(redirect)

def fundraiser_page(request, fundraiser_id=None):
    profile = get_object_or_404(FundRaiserProfile, pk=fundraiser_id)
    _extend_profile(profile)
    my_page = request.user.is_authenticated() and profile.user == request.user

    mentions = Mention.objects.select_related('tweeter').filter(
        link=profile).order_by('-when')
    uids = [m.tweeter.uid for m in mentions]
    top_supporters = TwitterUser.objects.filter(uid__in=uids).order_by('-followers')[:5]

    return render_to_response('fundraiser.html',
            {'fundraiser': profile,
             'recent_mentions': mentions[:5],
             'top_supporters': top_supporters,
             'my_page': my_page},
            context_instance=RequestContext(request))

def supporter_page(request, fundraiser_id=None, supporter_name=None):
    profile = get_object_or_404(FundRaiserProfile, pk=fundraiser_id)
    _extend_profile(profile)
    my_page = request.user.is_authenticated() and profile.user == request.user

    supporter = TwitterUser.objects.get(screen_name=supporter_name)
    mentions = Mention.objects.filter(tweeter=supporter, link=profile).order_by('-when')

    sticker = BRONZE
    if len(mentions) > 1:
        sticker = SILVER
    if supporter.has_donated:
        sticker = GOLD

    return render_to_response('supporter.html',
            {'fundraiser': profile,
             'supporter': supporter,
             'supporter_mentions': mentions,
             'my_page': my_page,
             'sticker': sticker},
            context_instance=RequestContext(request))

@return_json
def top_fundraisers(request):
    return _top_fundraisers()

class JustGivingBadgesJSONEncoder(json.JSONEncoder):
    def default(self, o):
        if isinstance(o, FundRaiserProfile):
            return {
                'page_id': o.jg_page_id,
                'page_score': o.page_score,
                'event_name': o.event_name,
                'total_raised': o.total_raised,
                'owner_name': o.owner_name,
            }
        elif isinstance(o, date):
            return o.isoformat()
        else:
            return json.JSONEncoder.default(self, o)

tweetrace/justgivingbadges/templates/base.html
<html>
<head>
    <title>{% block head_title %}JustGivingThanks{% endblock %}</title>
    <link rel="stylesheet" href="{{ STATIC_URL }}main.css" />
    <script data-main="{{ STATIC_URL }}scripts/main" src="{{ STATIC_URL }}scripts/require-jquery.js"></script>
</head>
<body>
    <header>
    <h1><a href="/">JustGivingThanks</a></h1>
        <p>Boost your Fundraising with your social network</p>
        {% if not supporter %}
        <img id="header-image" src="{{ STATIC_URL }}/img/gold_sticker_small.png" />
        {% endif %}
    </header>

    <div id="content">
        {% block content %}
            Welcome to Just Giving Thanks
        {% endblock %}
    </div>
</body>
</html>

tweetrace/justgivingbadges/templates/fundraiser.html
{% extends "base.html" %}

{% block content %}

    <h2>{{ fundraiser.owner_name }} is raising money for {{ fundraiser.event_name}}</h2>

    <section id="top_supporters">
        <h2>{{fundraiser.owner_name}}’s Top Supporters</h2>
        {% for supporter in top_supporters %}
            {% include "supporter_snippet.html" %}
        {% endfor %}
    </section>
    
    <section id="recent_mentions">
        <h2>Recent Support</h2>
        {% for mention in recent_mentions %}
            {% include "mention_snippet.html" %}
        {% endfor %}
    </section>

{% endblock %}

tweetrace/justgivingbadges/templates/fundraiser_snippet.html
<div class="fundraiser">
    <a href="/fundraiser/{{fundraiser.jg_page_id}}/">
    <img class="front_page_fundraiser" src="{{STATIC_URL}}img/fundraiser.png" />
        {{ fundraiser.owner_name }}
    </a>
    <div class="fundraiser_activity">
        {{ fundraiser.owner_name }} is raising money for {{ fundraiser.event_name }}
        <br />
        <strong>Social Promotion Score: <br />{{ fundraiser.page_score }}</strong>
    </div>
</div>

tweetrace/justgivingbadges/templates/give_form.html
{% block just_give %}
<section id="just-giving">
<form action="http://www.justgiving.com/donation/sponsor/page/3563163?amount=10&exitUrl=http%3a%2f%2fwww.justgivingthanks.com/fundraiser/{{fundraiser.jg_page_id}}?donationId=JUSTGIVING-DONATION-ID" method="">
        <input type="hidden" name="charityId" value="{{ fundraiser_id.jg_page_id }}">
        <input type="hidden" name="exitUrl" value="{% url fundraiser-page fundraiser.jg_page_id %}">
        <h2>Make a donation of £ <input class="text" type="text" name="amount" /> from <input type="text" value="Twitter Name" /> now at <button type="submit">Just Giving</button></h2>
    </form>
</section>
{% endblock %}

tweetrace/justgivingbadges/templates/home.html
{% extends "base.html" %}

{% block content %}

    {% if not fundraiser %}
        <br />
        <br />
        <div id="register">
            <h3>Link your Twitter Account and start connecting with your supporters!</h3>
            <a href="{% url register %}">Sign up</a>
        </div>
        <br />
        <br />
    {% endif %}

    
    <section id="top_fundraisers">
        <h3>Most successful social fundraisers</h3>
        <p>These fundraisers have been most successful at raising support through social networks:</p>
        <br />
        {% for fundraiser in top_fundraisers %}
                {% include "fundraiser_snippet.html" %}
        {% endfor %}
    </section>
    
{% endblock %}

tweetrace/justgivingbadges/templates/just_give.html
{% block just_give %}
<section id="just-giving">
    <form action="{{ giving.sdi.url }}{{ fundraiser.jg_page_id }}" method="">
        <input type="hidden" name="charityId" value="{{ fundraiser_id.jg_page_id }}">
        <input type="hidden" name="exitUrl" value="{% url fundraiser-page fundraiser.jg_page_id %}">
        <h2>Make a donation of £ <input class="text" type="text" name="amount" /> from <input type="text" value="Twitter Name" /> now at <button type="submit">Just Giving</button></h2>
    </form>
</section>
{% endblock %}

tweetrace/justgivingbadges/templates/mention_snippet.html
<div class="mention">
    <a href="{% url supporter-page fundraiser.jg_page_id mention.tweeter.screen_name %}"><img src="{{ mention.tweeter.profile_picture }}" /></a>
    <h4>{{mention.tweeter.screen_name}}</h4>
    <p>{{mention.text}}</p>
</div>

tweetrace/justgivingbadges/templates/registration.html
{% extends "base.html" %}

{% block content %}
  {% if form.errors %}
    <p class="error">Sorry, something went wrong</p>
  {% endif %}

  <p> 
    To connect you with your supporters on social networks, you will also need a valid JustGiving
    page. Additionally, we need your email and JustGiving Password in order to link up with your
    JustGiving account. Sorry about this - it's currently the only way to get access to the 
    JustGiving API.
    <br />
    <br />
    Once you've entered this information, you will be sent off to Twitter to connect your account.
    <br />
    <br />
    <br />


  <form action="" method="post">
    {% csrf_token %}
    <dl>
        <dt><label for="id_email">Your email address:</label></dt>
        <dd><input type="text" name="email" id="id_email" /></dd>
        <br />
        
        <dt><label for="id_jg_page">Your JustGiving Page:</label></dt>
        <dd><input type="text" name="jg_page" id="id_jg_page" /></dd>
        
        <br />
        <dt><label for="id_jg_password">Your JustGiving Password:</label></dt>
        <dd><input type="password" name="jg_password" id="id_jg_password" /></dd>
        <br />
    </dl>
    
    <input type="submit" value="Connect with Twitter" />
  </form>
{% endblock %}

tweetrace/justgivingbadges/templates/require.html
{% extends /base.html %}

{% block require %}

{% if variable $}
    <script type="text/javascript">
        require('{{ variable }}', function({{ variable }}){});
    </script>
{% endif %}

{% if other_variable %}
    <script type="text/javascript">
        require('{{ variable }}', function({{ variable }}){});
        define('some:info', {{ object }});
    </script>
{% endif %}

{% endblock %}

tweetrace/justgivingbadges/templates/success.html
{% extends "base.html" %}

{% block content %}
    <h1>You have registered successfully!</h1>
{% endblock %}

tweetrace/justgivingbadges/templates/supporter.html
{% extends "base.html" %}

fundraiser
supporter

{% block content %}
    <div id="sticker">
        {{ sticker }}
        <img src="{{ STATIC_URL }}{{sticker.image_url}}" />
    </div>
    <br />
    <br />
    <h3>{{supporter.screen_name}} has been supporting {{ fundraiser.owner_name}}!</h3>
    <br />
    <br />
    {% if supporter_mentions %}
        <h3>Support:</h3>
        <br />
        {% for mention in supporter_mentions %}
            {% include "mention_snippet.html" %}
        {% endfor %}
    {% endif %}

    {% include "give_form.html" %}
{% endblock %}

tweetrace/justgivingbadges/templates/supporter_snippet.html
<div class="supporter">
    <a href="{% url supporter-page fundraiser.jg_page_id supporter.screen_name %}"><img src="{{ supporter.profile_picture }}" />
        <br />
    {{supporter.screen_name}}</a>
    <p>{{supporter.followers}} followers</p>
</div>